// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-bkSq9ZcGhgPVRLb0gE5XisXub4nE1s',
    appId: '1:338065751697:web:9c57d1635d5e07969dc930',
    messagingSenderId: '338065751697',
    projectId: 'payment-app-23ff8',
    authDomain: 'payment-app-23ff8.firebaseapp.com',
    storageBucket: 'payment-app-23ff8.appspot.com',
    measurementId: 'G-57NK7R7T80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0b0JX9sqrfG6bI3L4Ni2eN8DhT6eGGY',
    appId: '1:338065751697:android:14f9f048fb80a2e39dc930',
    messagingSenderId: '338065751697',
    projectId: 'payment-app-23ff8',
    storageBucket: 'payment-app-23ff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvvUziGz4WcqDlMvmEaxogkW2ys9JBlq8',
    appId: '1:338065751697:ios:7d5e851abf7483b19dc930',
    messagingSenderId: '338065751697',
    projectId: 'payment-app-23ff8',
    storageBucket: 'payment-app-23ff8.appspot.com',
    iosClientId: '338065751697-e7j9vtder0skhou718sojk5i02p5ln3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvvUziGz4WcqDlMvmEaxogkW2ys9JBlq8',
    appId: '1:338065751697:ios:c429f1c8363825689dc930',
    messagingSenderId: '338065751697',
    projectId: 'payment-app-23ff8',
    storageBucket: 'payment-app-23ff8.appspot.com',
    iosClientId: '338065751697-lf4odpdeb07nm5prhejm6b6h6jc6kven.apps.googleusercontent.com',
    iosBundleId: 'com.example.paymentApp.RunnerTests',
  );
}
